name: let_tutor
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  retrofit: ^2.0.1

  #base
  analyzer: ^5.10.0
  flutter_bloc: ^8.1.1 
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.0.7
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.1.4
  url_launcher: ^6.0.17

  #utils
  mockito: ^5.4.0
  logger: ^1.0.0
  pedantic: ^1.11.1
  date_format: ^2.0.2
  connectivity_plus: ^2.0.3
  permission_handler: ^9.2.0
  image_picker: ^0.8.4+4
  extended_image: ^6.2.1
  image_editor: ^1.0.0
  file_picker: ^4.3.2
  uuid: ^3.0.4
  timeago: ^3.1.0
  mime: ^1.0.2
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  package_info: ^2.0.2 
  device_info: ^2.0.2 
  dartx: ^0.7.1
  enum_to_string: ^2.0.1
  jwt_decode: ^0.3.1
  equatable: ^2.0.5

  # services
  onesignal_flutter: ^3.2.3
  add_2_calendar: ^2.1.3
  shake: ^2.1.0
  clipboard: ^0.1.3

  # firebase
  firebase_core: ^1.18.0
  firebase_auth: ^3.1.5
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.1
  tab_indicator_styler: ^2.0.0

  #Hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #JSON
  json_annotation: ^4.6.0
  phone_numbers_parser: ^4.2.0
  flutter_multi_formatter: ^2.5.1
  expandable: ^5.0.1

  #ui
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.3
  dotted_border: ^2.0.0
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  flutter_rating_bar: ^4.0.1
  badges: ^2.0.2 
  pull_to_refresh_flutter3: ^2.0.1
  pin_code_fields: ^7.3.0
  webview_flutter: ^3.0.0
  video_thumbnail: ^0.5.2
  video_player: ^2.4.5
  chewie: ^1.3.3
  table_calendar: ^3.0.7
  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^5.0.6
  google_sign_in: ^5.4.2
  countries_utils: ^1.0.1
  sprintf: ^7.0.0
  jitsi_meet: ^4.0.0
  jwt_decoder: ^2.0.1
  pdf_render: ^1.3.6
  printing: ^5.9.3
  video_uploader: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^2.0.0
  json_serializable: ^6.2.0
  injectable_generator:
  module_generator:
    path: tools/module_generator
  


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true 

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
